[credentials.usernames.admin]
email = "admin@daadrasats.com"
name = "Daadras"
password = "$2b$12$dgh5Wrchedqc67kHN.Qhze7SLqm9l00qT9dSnoQrmf82dEC1twkJ."

[cookie]
expiry_days = 0
key = "aofnadbvsanc"
name = "cookie"

[preauthorized]
emails = []
