MAPBOX_ACCESS_TOKEN = "pk.eyJ1Ijoic2hvY2tlZHJ1bWJsZSIsImEiOiJjbHlycDVwZjEwNnViMmxyMDJ2NXlpeWRiIn0.q8928pDyTpw51xqJouSQrQ"

[google_drive_credentials]
credentials = '{"installed":{"client_id":"491302109831-v4rkv1b94dejfvt0704mapb8huvj6ct8.apps.googleusercontent.com","project_id":"graphite-byte-424914-n4","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["http://localhost"]}}'

[credentials.usernames.admin]
email = "admin@daadrasats.com"
name = "Daadras"
password = "$2b$12$dgh5Wrchedqc67kHN.Qhze7SLqm9l00qT9dSnoQrmf82dEC1twkJ."

[cookie]
expiry_days = 0
key = "aofnadbvsanc"
name = "cookie"

[preauthorized]
emails = []


